### ISSUE TITLE
entity package 관련 질문입니다.

### ISSUE THREAD

**Issue by HoJun-Seo** [HoJun-Seo/ks-web#2]
과제는 성공적으로 수행했습니다만
entity package 에서 SocialMedia 클래스나 Skill 클래스 같이 다른 클래스에 @GeneratedValue Annotation 을 쓰면 CommandLineRunner execute fail error 가 뜨는데
 그렇게 하지 않고 Person 클래스 에만 @GeneratedValue Annotation 을 사용하면 컴파일 및 웹 페이지가 정상적으로 잘 작동하는 것을 확인했습니다.
@GeneratedValue Annotation 이 기본키 매핑 전략이라는 것은 검색을 통해서 알아 냈는데, 왜 Person 클래스가 아닌 다른 클래스에 위의 어노테이션을 달아두면 에러가 생기는 걸까요?

**Comment by lns13301** [comment]
Person 클래스라서 에러가 발생한 것이 아니라, 다른 엔티티 객체에서 @GeneratedValue 어노테이션을 사용한 필드 타입이 String 이기 때문에 에러가 발생한 것입니다.
@GeneratedValue 어노테이션은 Integer 나 Long 과 같은 타입에 사용하여야 에러가 발생하지 않습니다.
다음부터 코드를 작성하실 때 Branch / Pull requests 를 이용하여 작성한다면 코드리뷰하기 더 용이할 것 같습니다.
